# Generated by Django 4.1.7 on 2023-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customaccount",
            name="pay_rate",
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
        ),
    ]
