# Generated by Django 4.1.7 on 2023-03-27 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0002_customaccount_pay_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customaccount",
            name="company_ID",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customaccount",
            name="employee_ID",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="customaccount",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customaccount",
            name="position",
            field=models.CharField(default="employee", max_length=50),
        ),
        migrations.AddField(
            model_name="customaccount",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 3, 27)),
        ),
    ]
