# Generated by Django 4.1.7 on 2023-03-27 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0004_alter_customaccount_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customaccount",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
