# Generated by Django 4.1.7 on 2023-03-09 23:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("time_log", "0002_workentry_delete_timefield"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_rate",
                    models.DecimalField(decimal_places=2, default=25, max_digits=10),
                ),
                ("date_logged", models.DateField(default=datetime.date.today)),
                ("num_hours", models.IntegerField(default=8)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WorkEntry",
        ),
    ]
