# Generated by Django 4.1.7 on 2023-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("time_log", "0003_timeentry_delete_workentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="num_hours",
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="pay_rate",
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
    ]
